/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CricketTeam {
  'id' : bigint,
  'country' : string,
  'name' : string,
  'wins' : bigint,
  'losses' : bigint,
  'matchesPlayed' : bigint,
  'flagUrl' : string,
  'ranking' : bigint,
}
export interface MatchScore {
  'id' : bigint,
  'matchType' : string,
  'status' : string,
  'team1' : string,
  'team2' : string,
  'venue' : string,
  'date' : Time,
  'score1' : bigint,
  'score2' : bigint,
}
export interface NewsArticle {
  'id' : bigint,
  'title' : string,
  'source' : string,
  'summary' : string,
  'imageUrl' : string,
  'timestamp' : Time,
  'category' : string,
}
export interface Player {
  'id' : bigint,
  'name' : string,
  'role' : string,
  'team' : string,
  'nationality' : string,
  'stats' : { 'runs' : bigint, 'average' : number, 'wickets' : bigint },
}
export type Time = bigint;
export interface _SERVICE {
  'addCricketTeam' : ActorMethod<
    [bigint, string, string, string, bigint, bigint, bigint, bigint],
    undefined
  >,
  'addMatchScore' : ActorMethod<
    [bigint, string, string, bigint, bigint, string, string, string, Time],
    undefined
  >,
  'addNewsArticle' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
  'addPlayer' : ActorMethod<
    [bigint, string, string, string, string, bigint, bigint, number],
    undefined
  >,
  'getAllCricketTeams' : ActorMethod<[], Array<CricketTeam>>,
  'getAllMatchScores' : ActorMethod<[], Array<MatchScore>>,
  'getAllNewsArticles' : ActorMethod<[], Array<NewsArticle>>,
  'getAllPlayers' : ActorMethod<[], Array<Player>>,
  'getNewsByCategory' : ActorMethod<[string], Array<NewsArticle>>,
  'getNewsById' : ActorMethod<[bigint], NewsArticle>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];