/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const CricketTeam = IDL.Record({
  'id' : IDL.Nat,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'matchesPlayed' : IDL.Nat,
  'flagUrl' : IDL.Text,
  'ranking' : IDL.Nat,
});
export const MatchScore = IDL.Record({
  'id' : IDL.Nat,
  'matchType' : IDL.Text,
  'status' : IDL.Text,
  'team1' : IDL.Text,
  'team2' : IDL.Text,
  'venue' : IDL.Text,
  'date' : Time,
  'score1' : IDL.Nat,
  'score2' : IDL.Nat,
});
export const NewsArticle = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'source' : IDL.Text,
  'summary' : IDL.Text,
  'imageUrl' : IDL.Text,
  'timestamp' : Time,
  'category' : IDL.Text,
});
export const Player = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'team' : IDL.Text,
  'nationality' : IDL.Text,
  'stats' : IDL.Record({
    'runs' : IDL.Nat,
    'average' : IDL.Float64,
    'wickets' : IDL.Nat,
  }),
});

export const idlService = IDL.Service({
  'addCricketTeam' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'addMatchScore' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Time,
      ],
      [],
      [],
    ),
  'addNewsArticle' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addPlayer' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
      ],
      [],
      [],
    ),
  'getAllCricketTeams' : IDL.Func([], [IDL.Vec(CricketTeam)], ['query']),
  'getAllMatchScores' : IDL.Func([], [IDL.Vec(MatchScore)], ['query']),
  'getAllNewsArticles' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
  'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getNewsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(NewsArticle)], ['query']),
  'getNewsById' : IDL.Func([IDL.Nat], [NewsArticle], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const CricketTeam = IDL.Record({
    'id' : IDL.Nat,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'matchesPlayed' : IDL.Nat,
    'flagUrl' : IDL.Text,
    'ranking' : IDL.Nat,
  });
  const MatchScore = IDL.Record({
    'id' : IDL.Nat,
    'matchType' : IDL.Text,
    'status' : IDL.Text,
    'team1' : IDL.Text,
    'team2' : IDL.Text,
    'venue' : IDL.Text,
    'date' : Time,
    'score1' : IDL.Nat,
    'score2' : IDL.Nat,
  });
  const NewsArticle = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'source' : IDL.Text,
    'summary' : IDL.Text,
    'imageUrl' : IDL.Text,
    'timestamp' : Time,
    'category' : IDL.Text,
  });
  const Player = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'team' : IDL.Text,
    'nationality' : IDL.Text,
    'stats' : IDL.Record({
      'runs' : IDL.Nat,
      'average' : IDL.Float64,
      'wickets' : IDL.Nat,
    }),
  });
  
  return IDL.Service({
    'addCricketTeam' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'addMatchScore' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Time,
        ],
        [],
        [],
      ),
    'addNewsArticle' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addPlayer' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'getAllCricketTeams' : IDL.Func([], [IDL.Vec(CricketTeam)], ['query']),
    'getAllMatchScores' : IDL.Func([], [IDL.Vec(MatchScore)], ['query']),
    'getAllNewsArticles' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
    'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getNewsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(NewsArticle)],
        ['query'],
      ),
    'getNewsById' : IDL.Func([IDL.Nat], [NewsArticle], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };